### ISSUE TITLE
CodeIgniter MongoDB Active Record Library Not Found

### ISSUE THREAD

**Issue by shujatdocs** [sepehr/ci-mongodb-ionauth#1]
It seems MongoDB Active Record Library has been deprecated and replaces with MongoQB, Can you please provide the "MongoDB Active Record Library" code if you have a copy, or else at least provide some help in working with MongoQB.

Thanks for your time

**Comment by sepehr** [comment]
You should really consider using an alternative to both the mongo AR library and this repository. The functionality has not been synced with the upstream repo for a long time.

However, if you need a copy of the mongodb AR library, I could find a modified (mostly minor fixes) version from an old project. Here it is:

https://gist.github.com/anonymous/c1ce000d42797444d858eea48b4540a5
